import { readFile, rename, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { isAbsolute, join, resolve } from "node:path";
import { parseModelAssignmentProfileOverlay } from "./ai-provider-profiles.js";
import {
	type ProviderScopeInput,
	readProviderScopeInput,
} from "./ai-provider-scope.js";

type JsonRecord = Record<string, unknown>;

export const MODEL_ASSIGNMENT_PROFILE_APPLY_TARGET = {
	PI: "pi",
	OPENCODE: "opencode",
} as const;

export type ModelAssignmentProfileApplyTarget =
	(typeof MODEL_ASSIGNMENT_PROFILE_APPLY_TARGET)[keyof typeof MODEL_ASSIGNMENT_PROFILE_APPLY_TARGET];

const PROTECTED_OPENCODE_AGENTS = new Set([
	"build",
	"plan",
	"gentle-orchestrator",
	"dangerous-gentleman",
	"title",
	"summary",
	"compaction",
]);

export interface ApplyModelAssignmentProfileOverlayOptions {
	overlayPath?: string;
	passListPath?: string;
	target: string;
	piSettingsPath?: string;
	opencodeConfigPath?: string;
	dryRun?: boolean;
	now?: Date;
}

export interface RollbackModelAssignmentProfileOverlayOptions {
	backupPath: string;
	target: string;
	piSettingsPath?: string;
	opencodeConfigPath?: string;
	dryRun?: boolean;
	now?: Date;
}

export interface ApplyModelAssignmentProfileOverlayResult {
	overlayPath?: string;
	target: ModelAssignmentProfileApplyTarget;
	dryRun: boolean;
	wrote: boolean;
	files: string[];
	backups: string[];
	passModels?: number;
}

interface SmokeReportEvidenceRow {
	status?: unknown;
	evidence?: unknown;
}

function isRecord(value: unknown): value is JsonRecord {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizePath(path: string): string {
	if (path.startsWith("~/")) return join(homedir(), path.slice(2));
	return isAbsolute(path) ? path : resolve(path);
}

function timestamp(now: Date): string {
	return now.toISOString().replace(/[-:]/g, "").replace(/\..+$/, "Z");
}

function parseJsonObject(content: string, path: string): JsonRecord {
	const parsed: unknown = JSON.parse(content);
	if (!isRecord(parsed)) throw new Error(`${path} must contain a JSON object`);
	return parsed;
}

function modelRef(provider: string, model: string): string {
	return `${provider}/${model}`;
}

function normalizeApplyTarget(
	target: string,
): ModelAssignmentProfileApplyTarget {
	if (target === "both") {
		throw new Error("profile-apply refuses --target both");
	}
	if (target === "codex") {
		throw new Error("profile-apply refuses --target codex");
	}
	if (
		target === MODEL_ASSIGNMENT_PROFILE_APPLY_TARGET.PI ||
		target === MODEL_ASSIGNMENT_PROFILE_APPLY_TARGET.OPENCODE
	) {
		return target;
	}
	throw new Error(`unknown target: ${target}`);
}

function requireTargetPath(
	target: ModelAssignmentProfileApplyTarget,
	options: {
		piSettingsPath?: string;
		opencodeConfigPath?: string;
	},
): string {
	if (target === MODEL_ASSIGNMENT_PROFILE_APPLY_TARGET.PI) {
		const path = options.piSettingsPath?.trim();
		if (!path) throw new Error("profile-apply requires --pi-settings");
		return normalizePath(path);
	}
	const path = options.opencodeConfigPath?.trim();
	if (!path) throw new Error("profile-apply requires --opencode-config");
	return normalizePath(path);
}

function assertReportIsNotDryRun(content: string, inputPath: string): void {
	for (const line of content.split(/\r?\n/)) {
		const trimmed = line.trim();
		if (!trimmed) continue;
		const row = JSON.parse(trimmed) as SmokeReportEvidenceRow;
		if (row.status === "dry_run" || row.evidence === "dry-run") {
			throw new Error(
				`${inputPath} was generated by smoke-test --dry-run; run real smoke probes before applying model assignment profiles`,
			);
		}
	}
}

async function assertPassListCanBeApplied(
	inputPath: string,
	input: ProviderScopeInput,
): Promise<void> {
	if (input.sourceKind === "report") {
		assertReportIsNotDryRun(await readFile(inputPath, "utf8"), inputPath);
	}
	if (input.passModels.length === 0) {
		throw new Error(
			`${inputPath} contains no passing models; run real smoke probes before applying model assignment profiles`,
		);
	}
}

function requiredOverlayRefs(
	overlay: ReturnType<typeof parseModelAssignmentProfileOverlay>,
): string[] {
	const refs: string[] = [];
	for (const row of overlay.routing) {
		if (row.primary !== null) refs.push(row.primary);
	}
	for (const profile of Object.values(overlay.profiles)) {
		if (profile.primaryRef !== null) refs.push(profile.primaryRef);
	}
	return [...new Set(refs)];
}

function snapshot(value: unknown): string {
	return JSON.stringify(value) ?? "undefined";
}

function assertPiDefaultsUnchanged(
	before: JsonRecord,
	after: JsonRecord,
): void {
	for (const key of [
		"defaultProvider",
		"defaultModel",
		"enabledModels",
	] as const) {
		if (snapshot(before[key]) !== snapshot(after[key])) {
			throw new Error(`profile-apply must not change Pi ${key}`);
		}
	}
}

function mergePiModelProfiles(
	settings: JsonRecord,
	overlay: ReturnType<typeof parseModelAssignmentProfileOverlay>,
): JsonRecord {
	const existing = isRecord(settings.modelProfiles)
		? settings.modelProfiles
		: {};
	const next: JsonRecord = {
		...settings,
		modelProfiles: {
			...existing,
			profiles: overlay.profiles,
			routing: overlay.routing,
		},
	};
	assertPiDefaultsUnchanged(settings, next);
	return next;
}

function applyOpenCodeRouting(
	config: JsonRecord,
	overlay: ReturnType<typeof parseModelAssignmentProfileOverlay>,
): JsonRecord {
	const agentMap = config.agent;
	if (!isRecord(agentMap)) {
		throw new Error("OpenCode config has no agent object");
	}
	const nextAgents: JsonRecord = { ...agentMap };
	for (const row of overlay.routing) {
		if (PROTECTED_OPENCODE_AGENTS.has(row.phase)) {
			throw new Error(
				`profile-apply refuses protected OpenCode agent: ${row.phase}`,
			);
		}
		const agent = agentMap[row.phase];
		if (!isRecord(agent)) {
			throw new Error(
				`OpenCode config is missing routed agent phase: ${row.phase}`,
			);
		}
		if (row.primary === null) continue;
		nextAgents[row.phase] = { ...agent, model: row.primary };
	}
	const next: JsonRecord = { ...config, agent: nextAgents };
	if (snapshot(config.provider) !== snapshot(next.provider)) {
		throw new Error("profile-apply must not change OpenCode provider");
	}
	return next;
}

async function writeJsonWithExclusiveBackup(options: {
	path: string;
	value: JsonRecord;
	dryRun: boolean;
	now: Date;
}): Promise<string> {
	const backupPath = `${options.path}.bak-${timestamp(options.now)}`;
	if (options.dryRun) return backupPath;
	const original = await readFile(options.path, "utf8");
	await writeFile(backupPath, original, { flag: "wx" });
	const tmpPath = `${options.path}.apply-tmp-${timestamp(options.now)}`;
	await writeFile(tmpPath, `${JSON.stringify(options.value, null, 2)}\n`, {
		flag: "wx",
	});
	await rename(tmpPath, options.path);
	return backupPath;
}

export async function applyModelAssignmentProfileOverlay(
	options: ApplyModelAssignmentProfileOverlayOptions,
): Promise<ApplyModelAssignmentProfileOverlayResult> {
	const target = normalizeApplyTarget(options.target);
	const overlayPath = options.overlayPath?.trim();
	if (!overlayPath) {
		throw new Error("profile-apply requires <overlay.json>");
	}
	const passListPath = options.passListPath?.trim();
	if (!passListPath) {
		throw new Error(
			"profile-apply requires --pass-list <pass.tsv|report.jsonl>",
		);
	}
	const resolvedOverlayPath = normalizePath(overlayPath);
	const resolvedPassListPath = normalizePath(passListPath);
	const destPath = requireTargetPath(target, options);
	const dryRun = options.dryRun ?? false;
	const now = options.now ?? new Date();
	const overlay = parseModelAssignmentProfileOverlay(
		await readFile(resolvedOverlayPath, "utf8"),
		resolvedOverlayPath,
	);
	if (overlay.target !== target) {
		throw new Error(
			`overlay target ${overlay.target} does not match --target ${target}`,
		);
	}
	const input = await readProviderScopeInput(resolvedPassListPath);
	await assertPassListCanBeApplied(resolvedPassListPath, input);
	const passRefs = new Set(
		input.passModels.map((model) => modelRef(model.provider, model.model)),
	);
	const missing = requiredOverlayRefs(overlay).filter(
		(ref) => !passRefs.has(ref),
	);
	if (missing.length) {
		throw new Error(
			`overlay references models missing from pass evidence: ${missing.join(", ")}`,
		);
	}

	const current = parseJsonObject(await readFile(destPath, "utf8"), destPath);
	const next =
		target === MODEL_ASSIGNMENT_PROFILE_APPLY_TARGET.PI
			? mergePiModelProfiles(current, overlay)
			: applyOpenCodeRouting(current, overlay);
	const backupPath = await writeJsonWithExclusiveBackup({
		path: destPath,
		value: next,
		dryRun,
		now,
	});

	return {
		overlayPath: resolvedOverlayPath,
		target,
		dryRun,
		wrote: !dryRun,
		files: [destPath],
		backups: [backupPath],
		passModels: input.passModels.length,
	};
}

export async function rollbackModelAssignmentProfileOverlay(
	options: RollbackModelAssignmentProfileOverlayOptions,
): Promise<ApplyModelAssignmentProfileOverlayResult> {
	const target = normalizeApplyTarget(options.target);
	const destPath = requireTargetPath(target, options);
	const backupPath = normalizePath(options.backupPath);
	const dryRun = options.dryRun ?? false;
	const now = options.now ?? new Date();
	const safetyPath = `${destPath}.pre-rollback-${timestamp(now)}`;
	try {
		await readFile(backupPath);
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === "ENOENT") {
			throw new Error(`backup not found: ${backupPath}`);
		}
		throw error;
	}
	const backups = [backupPath];
	if (!dryRun) {
		try {
			const current = await readFile(destPath, "utf8");
			await writeFile(safetyPath, current, { flag: "wx" });
			backups.push(safetyPath);
		} catch (error) {
			if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
		}
		const restored = await readFile(backupPath, "utf8");
		const tmpPath = `${destPath}.rollback-tmp-${timestamp(now)}`;
		await writeFile(tmpPath, restored, { flag: "wx" });
		await rename(tmpPath, destPath);
	}
	return {
		target,
		dryRun,
		wrote: !dryRun,
		files: [destPath],
		backups,
	};
}
