#!/bin/bash
# =============================================================================
# COMMIT-MSG TEST SUITE
# =============================================================================
# Valida que el hook commit-msg bloquea AI attribution en TODAS las variantes
# conocidas, incluyendo bypasses identificados en auditoría 2026-05-17.
#
# Uso:
#   ./commit-msg.test.sh
#
# Exit code 0 = todos los tests pasan
# Exit code 1 = al menos un test falla
# =============================================================================

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
HOOK="$SCRIPT_DIR/commit-msg"

if [ ! -x "$HOOK" ]; then
    echo "ERROR: commit-msg hook not found or not executable: $HOOK"
    exit 1
fi

PASS=0
FAIL=0
FAILED_TESTS=()

# expect_block <description> <message>
# El hook debe BLOQUEAR este mensaje (exit != 0)
expect_block() {
    local desc="$1"
    local msg="$2"
    local tmpfile
    tmpfile=$(mktemp)
    printf "%s" "$msg" > "$tmpfile"
    if "$HOOK" "$tmpfile" >/dev/null 2>&1; then
        FAIL=$((FAIL + 1))
        FAILED_TESTS+=("[NOT BLOCKED] $desc | msg: '$msg'")
        echo "  FAIL: $desc (should block but passed): '$msg'"
    else
        PASS=$((PASS + 1))
    fi
    rm -f "$tmpfile"
}

# expect_pass <description> <message>
# El hook debe PERMITIR este mensaje (exit 0)
expect_pass() {
    local desc="$1"
    local msg="$2"
    local tmpfile
    tmpfile=$(mktemp)
    printf "%s" "$msg" > "$tmpfile"
    if "$HOOK" "$tmpfile" >/dev/null 2>&1; then
        PASS=$((PASS + 1))
    else
        FAIL=$((FAIL + 1))
        FAILED_TESTS+=("[FALSE POSITIVE] $desc | msg: '$msg'")
        echo "  FAIL: $desc (should pass but blocked): '$msg'"
    fi
    rm -f "$tmpfile"
}

echo "=== Running commit-msg hook test suite ==="
echo ""

# ─── Cases que DEBEN bloquear ────────────────────────────────────────

# Co-authored-by con cada proveedor
expect_block "Co-authored-by Claude" "feat: add foo

Co-authored-by: Claude <claude@anthropic.com>"

expect_block "Co-authored-by claude lowercase" "feat: bar

co-authored-by: claude <c@a.com>"

expect_block "Co-authored-by double space" "feat: baz

Co-authored-by:  Claude <c@a.com>"

expect_block "Co-authored-by GPT" "feat: x

Co-authored-by: GPT-4 <g@o.com>"

expect_block "Co-authored-by Copilot" "feat: y

Co-authored-by: GitHub Copilot <c@gh.com>"

expect_block "Co-authored-by ai standalone" "feat: z

Co-authored-by: AI Assistant <a@b.com>"

# Made/Generated/Written/Created by/with X — single space
expect_block "Made by Claude" "feat: add Made by Claude"
expect_block "Made with Claude" "feat: Made with Claude"
expect_block "Generated by GPT" "feat: Generated by GPT"
expect_block "Written with OpenAI" "fix: Written with OpenAI"
expect_block "Created by Anthropic" "feat: Created by Anthropic"
expect_block "Assisted by AI" "feat: Assisted by AI"
expect_block "Built with Gemini" "feat: Built with Gemini"
expect_block "Developed with Copilot" "feat: Developed with Copilot"
expect_block "Authored by LLM" "feat: Authored by LLM"

# Made/Generated/etc — DOUBLE space (bypass identificado en audit)
expect_block "Made by  Claude (double space)" "feat: Made by  Claude"
expect_block "Generated with  GPT (double space)" "fix: Generated with  GPT"
expect_block "Made by\tClaude (tab)" "$(printf 'feat: Made by\tClaude')"

# With help from X
expect_block "With help from Claude" "feat: x

With help from Claude"
expect_block "with help from GPT-4" "feat: with help from GPT-4"

# X-assisted variants (bypass identificado)
expect_block "anthropic-assisted" "feat: anthropic-assisted refactor"
expect_block "openai-assisted" "feat: openai-assisted change"
expect_block "ai-assisted" "feat: ai-assisted commit"
expect_block "Claude assisted (space)" "feat: Claude assisted work"
expect_block "LLM_assisted (underscore)" "feat: llm_assisted feature"

# Tool branding
expect_block "claude code" "feat: built with claude code"
expect_block "claude-code" "feat: via claude-code"
expect_block "claude_code" "feat: claude_code generated"
expect_block "GitHub Copilot" "feat: GitHub Copilot helped"
expect_block "Microsoft Copilot" "feat: Microsoft Copilot did this"

# Claude model variants (bypass identificado)
expect_block "claude opus (space)" "feat: claude opus tested"
expect_block "claude-sonnet (dash)" "feat: claude-sonnet used"
expect_block "claude_haiku (underscore)" "feat: claude_haiku approach"
expect_block "Claude3.5" "feat: Claude3.5 wrote this"
expect_block "claude4.7" "feat: claude4.7 contributed"
expect_block "Claude 4" "feat: Claude 4 logic"

# GPT model variants
expect_block "gpt-4" "feat: gpt-4 reviewed"
expect_block "gpt 5" "feat: gpt 5 wrote"
expect_block "gpt_3" "feat: gpt_3 helped"
expect_block "GPT4" "feat: GPT4 was used"

# ChatGPT
expect_block "ChatGPT" "feat: ChatGPT generated"
expect_block "chatgpt" "feat: powered by chatgpt"

# Emails
expect_block "@anthropic.com" "feat: x

Author: foo@anthropic.com"
expect_block "@openai.com" "feat: y

Co-authored-by: bot@openai.com"
expect_block "noreply@anthropic" "feat: noreply@anthropic.example"

# ─── Cases que DEBEN PASAR (false positive checks) ────────────────────

expect_pass "Simple feat" "feat: add user profile endpoint"
expect_pass "Simple fix" "fix: handle empty array in parser"
expect_pass "Refactor" "refactor: extract auth into middleware"
expect_pass "Docs" "docs: clarify install instructions"
expect_pass "Multi-line valid commit" "feat: add search

Implements full-text search using PostgreSQL FTS.
Includes integration tests."
expect_pass "Author named Claude (not attribution)" "feat: add user named Claude in seed data"
expect_pass "AI as acronym in product name" "feat: integrate with PaiAi API gateway"
expect_pass "Word 'made' without AI context" "feat: changes I made last week to the parser"

# ─── Summary ──────────────────────────────────────────────────────────

echo ""
echo "=== Results ==="
echo "  Passed: $PASS"
echo "  Failed: $FAIL"
echo ""

if [ $FAIL -gt 0 ]; then
    echo "Failed tests:"
    for t in "${FAILED_TESTS[@]}"; do
        echo "  - $t"
    done
    exit 1
fi

echo "All tests passed."
exit 0
