/**
 * Supply chain protection — configures Socket Firewall and enforces
 * minimum package release age to protect against typosquatting,
 * dependency confusion, and malicious package takeovers.
 */

import fs from "fs-extra";
import path from "path";
import type { Stack } from "../types/index.js";

// ── Types ──

export type PackageManager = "npm" | "pnpm" | "yarn" | "pip" | "cargo" | "go";

export interface SupplyChainConfig {
	packageManager: PackageManager;
	minReleaseAgeHours: number;
	socketEnabled: boolean;
	enforceLockfile: boolean;
}

export interface SupplyChainResult {
	configWritten: string[];
	warnings: string[];
}

// ── Detection ──

export function detectPackageManager(projectDir: string): PackageManager {
	if (fs.existsSync(path.join(projectDir, "pnpm-lock.yaml"))) return "pnpm";
	if (fs.existsSync(path.join(projectDir, "yarn.lock"))) return "yarn";
	if (fs.existsSync(path.join(projectDir, "package-lock.json"))) return "npm";
	if (fs.existsSync(path.join(projectDir, "Pipfile.lock"))) return "pip";
	if (fs.existsSync(path.join(projectDir, "Cargo.lock"))) return "cargo";
	if (fs.existsSync(path.join(projectDir, "go.sum"))) return "go";
	if (fs.existsSync(path.join(projectDir, "package.json"))) return "npm";
	return "npm";
}

export function stackForPM(pm: PackageManager): Stack {
	switch (pm) {
		case "npm":
		case "pnpm":
		case "yarn":
			return "node";
		case "pip":
			return "python";
		case "cargo":
			return "rust";
		case "go":
			return "go";
	}
}

// ── Socket Firewall config ──

export function buildSocketConfig(pm: PackageManager): Record<string, unknown> {
	return {
		version: 2,
		projectType: stackForPM(pm),
		issueRules: {
			"pkg:npm/*": {
				installScripts: "error",
				telemetry: "warn",
				troll: "error",
				unpublished: "error",
				deprecated: "warn",
				unmaintained: "warn",
				"new-author": "warn",
				shellAccess: "error",
				filesystemAccess: "warn",
				networkAccess: "warn",
				envAccess: "warn",
			},
		},
	};
}

// ── npmrc / lockfile enforcement ──

export function buildNpmrcLines(minAgeHours: number): string[] {
	const lines = [
		"# Supply chain protection — generated by javi-forge",
		"engine-strict=true",
		"save-exact=true",
	];
	if (minAgeHours > 0) {
		lines.push(
			`# Minimum package age: ${minAgeHours}h (enforced via CI/pre-install hook)`,
		);
	}
	return lines;
}

// ── Orchestrator ──

export async function configureSupplyChain(
	projectDir: string,
	options: Partial<SupplyChainConfig> = {},
): Promise<SupplyChainResult> {
	const pm = options.packageManager ?? detectPackageManager(projectDir);
	const minAge = options.minReleaseAgeHours ?? 48;
	const socketEnabled = options.socketEnabled ?? true;
	const enforceLockfile = options.enforceLockfile ?? true;

	const configWritten: string[] = [];
	const warnings: string[] = [];

	// 1. Socket Firewall config
	if (socketEnabled) {
		const socketPath = path.join(projectDir, ".socketrc");
		await fs.writeJson(socketPath, buildSocketConfig(pm), { spaces: 2 });
		configWritten.push(".socketrc");
	}

	// 2. npmrc for node projects
	if (stackForPM(pm) === "node") {
		const npmrcPath = path.join(projectDir, ".npmrc");
		const lines = buildNpmrcLines(minAge);

		if (enforceLockfile) {
			if (pm === "pnpm") {
				lines.push("frozen-lockfile=true");
			} else {
				lines.push("package-lock=true");
			}
		}

		// Append to existing .npmrc if present
		const existing = (await fs.pathExists(npmrcPath))
			? await fs.readFile(npmrcPath, "utf-8")
			: "";

		const newContent = existing
			? `${existing.trimEnd()}\n\n${lines.join("\n")}\n`
			: `${lines.join("\n")}\n`;

		await fs.writeFile(npmrcPath, newContent);
		configWritten.push(".npmrc");
	}

	// 3. Supply chain metadata in baseline dir
	const metaPath = path.join(projectDir, ".javi-forge", "supply-chain.json");
	await fs.ensureDir(path.dirname(metaPath));
	await fs.writeJson(
		metaPath,
		{
			packageManager: pm,
			minReleaseAgeHours: minAge,
			socketEnabled,
			enforceLockfile,
			configuredAt: new Date().toISOString(),
		},
		{ spaces: 2 },
	);
	configWritten.push(".javi-forge/supply-chain.json");

	if (!socketEnabled) {
		warnings.push(
			"Socket Firewall disabled. Consider enabling it for supply chain protection.",
		);
	}

	return { configWritten, warnings };
}
