import fs from 'fs-extra'
import path from 'path'
import type { SyncOptions, InitStep, AI_CLI } from '../types/index.js'
import { ensureDirExists } from '../lib/common.js'
import { parseFrontmatter } from '../lib/frontmatter.js'
import {
  AI_CONFIG_DIR,
  AI_CLI_CONFIG_FILES,
  MARKER_START,
  MARKER_END,
} from '../constants.js'

type StepCallback = (step: InitStep) => void

const ALL_TARGETS: AI_CLI[] = ['claude', 'opencode', 'gemini', 'qwen', 'codex', 'copilot']

function report(onStep: StepCallback, id: string, label: string, status: InitStep['status'], detail?: string) {
  onStep({ id, label, status, detail })
}

/** Read .skillignore and parse exclusion rules */
async function loadSkillIgnore(configDir: string): Promise<{
  globalExcludes: Set<string>
  targetExcludes: Map<string, Set<string>>
}> {
  const globalExcludes = new Set<string>()
  const targetExcludes = new Map<string, Set<string>>()

  const ignorePath = path.join(configDir, '.skillignore')
  if (!await fs.pathExists(ignorePath)) {
    return { globalExcludes, targetExcludes }
  }

  const content = await fs.readFile(ignorePath, 'utf-8')
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue

    if (line.includes(':')) {
      const [target, skill] = line.split(':', 2)
      if (target && skill) {
        if (!targetExcludes.has(target)) targetExcludes.set(target, new Set())
        targetExcludes.get(target)!.add(skill)
      }
    } else {
      globalExcludes.add(line)
    }
  }

  return { globalExcludes, targetExcludes }
}

/** Recursively collect agent/skill markdown files from a directory */
async function collectMarkdownEntries(
  baseDir: string,
  prefix = ''
): Promise<Array<{ relativePath: string; name: string; content: string }>> {
  const entries: Array<{ relativePath: string; name: string; content: string }> = []

  if (!await fs.pathExists(baseDir)) return entries

  const items = await fs.readdir(baseDir, { withFileTypes: true })
  for (const item of items) {
    if (item.name.startsWith('_') || item.name.startsWith('.')) continue

    const itemPath = path.join(baseDir, item.name)
    const relPath = prefix ? `${prefix}/${item.name}` : item.name

    if (item.isDirectory()) {
      // Look for SKILL.md or agent markdown inside
      const skillMd = path.join(itemPath, 'SKILL.md')
      if (await fs.pathExists(skillMd)) {
        const content = await fs.readFile(skillMd, 'utf-8')
        entries.push({ relativePath: relPath, name: item.name, content })
      } else {
        // Recurse into subcategory directories
        const subEntries = await collectMarkdownEntries(itemPath, relPath)
        entries.push(...subEntries)
      }
    } else if (item.name.endsWith('.md') && item.name !== 'README.md') {
      const content = await fs.readFile(itemPath, 'utf-8')
      const name = item.name.replace('.md', '')
      entries.push({ relativePath: relPath, name, content })
    }
  }

  return entries
}

/** Build a CLAUDE.md / GEMINI.md / etc from agents + skills */
function buildConfigContent(
  target: AI_CLI,
  agents: Array<{ name: string; content: string }>,
  skills: Array<{ name: string; relativePath: string; content: string }>
): string {
  const lines: string[] = []

  lines.push(`# AI Configuration for ${target}`)
  lines.push('')
  lines.push(`Auto-generated by javi-forge sync. Do not edit between markers.`)
  lines.push('')

  if (agents.length > 0) {
    lines.push('## Agents')
    lines.push('')
    for (const agent of agents) {
      const fm = parseFrontmatter(agent.content)
      if (fm?.data) {
        const desc = fm.data['description'] ?? ''
        lines.push(`- **${agent.name}**: ${desc}`)
      } else {
        lines.push(`- **${agent.name}**`)
      }
    }
    lines.push('')
  }

  if (skills.length > 0) {
    lines.push('## Available Skills')
    lines.push('')
    for (const skill of skills) {
      const fm = parseFrontmatter(skill.content)
      if (fm?.data) {
        const desc = fm.data['description'] ?? ''
        lines.push(`- **${skill.name}**: ${desc}`)
      } else {
        lines.push(`- **${skill.name}**`)
      }
    }
    lines.push('')
  }

  return lines.join('\n')
}

/** Merge generated content into an existing file using markers */
function mergeWithMarkers(existingContent: string, generatedContent: string): string {
  const startIdx = existingContent.indexOf(MARKER_START)
  const endIdx = existingContent.indexOf(MARKER_END)

  const markerBlock = `${MARKER_START}\n${generatedContent}\n${MARKER_END}`

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace existing marker block
    return existingContent.slice(0, startIdx) + markerBlock + existingContent.slice(endIdx + MARKER_END.length)
  }

  // Append marker block
  return existingContent.trimEnd() + '\n\n' + markerBlock + '\n'
}

/**
 * Sync AI config to a project directory, generating CLI-specific config files.
 */
export async function syncAIConfig(
  options: SyncOptions,
  onStep: StepCallback
): Promise<void> {
  const { target, mode, projectDir, dryRun } = options
  const targets = target === 'all' ? ALL_TARGETS : [target]
  const configDir = AI_CONFIG_DIR

  // Load exclusions
  const { globalExcludes, targetExcludes } = await loadSkillIgnore(configDir)

  // Collect agents and skills
  const agentsDir = path.join(configDir, 'agents')
  const skillsDir = path.join(configDir, 'skills')

  const allAgents = await collectMarkdownEntries(agentsDir)
  const allSkills = await collectMarkdownEntries(skillsDir)

  for (const cli of targets) {
    const stepId = `sync-${cli}`
    report(onStep, stepId, `Sync config for ${cli}`, 'running')

    try {
      // Filter out excluded skills
      const cliExcludes = targetExcludes.get(cli) ?? new Set()
      const filteredSkills = allSkills.filter(s => {
        const nameWithoutExt = s.name
        const relWithoutExt = s.relativePath.replace(/\.md$/, '').replace(/\/SKILL\.md$/, '')
        return !globalExcludes.has(nameWithoutExt)
          && !globalExcludes.has(relWithoutExt)
          && !cliExcludes.has(nameWithoutExt)
          && !cliExcludes.has(relWithoutExt)
      })

      const filteredAgents = allAgents.filter(a => {
        return !globalExcludes.has(a.name) && !cliExcludes.has(a.name)
      })

      // Build the config content
      const generatedContent = buildConfigContent(cli, filteredAgents, filteredSkills)

      // Determine destination
      const configFileName = AI_CLI_CONFIG_FILES[cli]
      if (!configFileName) {
        report(onStep, stepId, `Sync config for ${cli}`, 'skipped', 'no config file mapping')
        continue
      }

      const destPath = path.join(projectDir, configFileName)

      if (!dryRun) {
        await ensureDirExists(path.dirname(destPath))

        if (mode === 'merge' && await fs.pathExists(destPath)) {
          const existing = await fs.readFile(destPath, 'utf-8')
          const merged = mergeWithMarkers(existing, generatedContent)
          await fs.writeFile(destPath, merged, 'utf-8')
        } else {
          await fs.writeFile(destPath, generatedContent, 'utf-8')
        }
      }

      report(onStep, stepId, `Sync config for ${cli}`, 'done',
        `${filteredAgents.length} agents, ${filteredSkills.length} skills → ${configFileName}`)

      // Sync Claude commands if target is claude
      if (cli === 'claude') {
        const cmdStepId = `sync-${cli}-commands`
        report(onStep, cmdStepId, 'Sync Claude commands', 'running')
        try {
          const commandsSrc = path.join(configDir, 'commands')
          if (await fs.pathExists(commandsSrc)) {
            const commandsDest = path.join(projectDir, '.claude', 'commands')
            if (!dryRun) {
              await ensureDirExists(commandsDest)
              await fs.copy(commandsSrc, commandsDest, { overwrite: true })
            }
            const cmdFiles = await fs.readdir(commandsSrc)
            report(onStep, cmdStepId, 'Sync Claude commands', 'done', `${cmdFiles.length} commands`)
          } else {
            report(onStep, cmdStepId, 'Sync Claude commands', 'skipped', 'no commands dir')
          }
        } catch (e) {
          report(onStep, cmdStepId, 'Sync Claude commands', 'error', String(e))
        }
      }
    } catch (e) {
      report(onStep, stepId, `Sync config for ${cli}`, 'error', String(e))
    }
  }
}
