/**
 * Hooks verified by EXECUTION, not by grepping substrings.
 *
 * The hooks are installed into a real git repo and then run the way git runs
 * them: the file is executed directly so its `#!/bin/bash` shebang decides the
 * interpreter. (Running them through `sh` would pick dash on Debian-family
 * systems and break the bash arrays in `commit-msg`, producing a failure that
 * says nothing about the hook.)
 *
 * `pre-commit` / `pre-push` are exercised against a stub `javi-forge` (and a
 * stub `docker`) placed FIRST on PATH, so the frozen flag string and the
 * exit-code propagation are observed rather than assumed.
 */

import { execFile, execFileSync } from "node:child_process";
import path from "node:path";
import { promisify } from "node:util";
import fs from "fs-extra";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { installCIHooks } from "../commands/ci.js";
import { cleanupTempDir, createTempDir } from "./helpers.js";

const execFileAsync = promisify(execFile);

/**
 * Frozen hook contract (S1b): each shim execs the dispatcher `hooks run <name>`,
 * NOT `ci --quick …` directly. The dispatcher decides which sections run from
 * the `hooks:` config; the shim only forwards the hook name and propagates the
 * exit code.
 */
const FROZEN_PRE_COMMIT_ARGS = "hooks run pre-commit";
const FROZEN_PRE_PUSH_ARGS = "hooks run pre-push";

interface HookRunResult {
	exitCode: number;
	stdout: string;
	stderr: string;
}

let tmpDir: string;
let stubDir: string;
let argsLog: string;

/**
 * Write an executable stub that records its argv and exits with the value of
 * its OWN env var, so the CLI and Docker exit codes are controlled separately.
 */
async function writeStub(name: string, exitVar: string): Promise<void> {
	await fs.writeFile(
		path.join(stubDir, name),
		`#!/bin/bash\nprintf '%s\\n' "$*" >> "$STUB_ARGS_LOG"\nexit "\${${exitVar}:-0}"\n`,
		{ mode: 0o755 },
	);
}

async function runHook(
	name: string,
	args: string[] = [],
	env: Record<string, string> = {},
): Promise<HookRunResult> {
	const hookPath = path.join(tmpDir, ".git", "hooks", name);
	try {
		const { stdout, stderr } = await execFileAsync(hookPath, args, {
			cwd: tmpDir,
			env: {
				...process.env,
				PATH: `${stubDir}${path.delimiter}${process.env.PATH ?? ""}`,
				STUB_ARGS_LOG: argsLog,
				...env,
			},
		});
		return { exitCode: 0, stdout, stderr };
	} catch (e) {
		const err = e as { code?: number; stdout?: string; stderr?: string };
		return {
			exitCode: typeof err.code === "number" ? err.code : 1,
			stdout: err.stdout ?? "",
			stderr: err.stderr ?? "",
		};
	}
}

async function readArgsLog(): Promise<string[]> {
	if (!(await fs.pathExists(argsLog))) return [];
	return (await fs.readFile(argsLog, "utf-8"))
		.split("\n")
		.filter((line) => line.length > 0);
}

/** Write a commit message file and run commit-msg against it. */
async function runCommitMsg(message: string): Promise<HookRunResult> {
	const msgFile = path.join(tmpDir, "COMMIT_EDITMSG_FIXTURE");
	await fs.writeFile(msgFile, message);
	return runHook("commit-msg", [msgFile]);
}

describe("installed hooks — executed", () => {
	beforeEach(async () => {
		tmpDir = await createTempDir("javi-forge-hooks-exec-");
		execFileSync("git", ["init"], { cwd: tmpDir });
		stubDir = path.join(tmpDir, "stub-bin");
		await fs.ensureDir(stubDir);
		argsLog = path.join(tmpDir, "stub-args.log");
		await writeStub("javi-forge", "STUB_EXIT_CLI");
		await writeStub("docker", "STUB_EXIT_DOCKER");

		const { errors } = await installCIHooks(tmpDir);
		expect(errors).toEqual([]);
	});

	afterEach(async () => {
		await cleanupTempDir(tmpDir);
	});

	// ── commit-msg ────────────────────────────────────────────────────────────

	const BLOCKED_MESSAGES: Array<{ name: string; message: string }> = [
		{
			name: "co-authored-by claude",
			message:
				"feat: add parser\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
		},
		{
			name: "co-authored-by copilot",
			message:
				"fix: patch\n\nco-authored-by: GitHub Copilot <bot@github.com>\n",
		},
		{ name: "generated by ai", message: "chore: cleanup (generated by AI)\n" },
		{ name: "made by gpt", message: "docs: readme made by GPT\n" },
		{ name: "claude code marker", message: "feat: done with Claude Code\n" },
		{ name: "chatgpt marker", message: "refactor: asked ChatGPT for this\n" },
		{ name: "openai email", message: "feat: x\n\nContact: bot@openai.com\n" },
		{
			name: "claude-session trailer",
			message:
				"feat: add parser\n\nClaude-Session: https://claude.ai/code/session_01NZExampleId\n",
		},
	];

	const ALLOWED_MESSAGES: Array<{ name: string; message: string }> = [
		{ name: "plain feat", message: "feat(ci): add characterization tests\n" },
		{ name: "plain fix", message: "fix: correct off-by-one in parser\n" },
		{ name: "release commit", message: "chore(release): 1.7.0 [skip ci]\n" },
		{
			name: "human co-author",
			message:
				"feat: pair work\n\nCo-Authored-By: Ada Lovelace <ada@example.com>\n",
		},
	];

	it.each(BLOCKED_MESSAGES)("commit-msg blocks AI attribution: $name", async ({
		message,
	}) => {
		const result = await runCommitMsg(message);

		expect(result.exitCode).toBe(1);
		expect(result.stdout).toContain("COMMIT BLOCKED");
	});

	it.each(ALLOWED_MESSAGES)("commit-msg allows a clean message: $name", async ({
		message,
	}) => {
		const result = await runCommitMsg(message);

		expect(result.exitCode).toBe(0);
		expect(result.stdout).not.toContain("COMMIT BLOCKED");
	});

	// ── pre-commit ────────────────────────────────────────────────────────────

	it("pre-commit invokes the dispatcher with the frozen `hooks run` args", async () => {
		const result = await runHook("pre-commit");

		expect(result.exitCode).toBe(0);
		expect(await readArgsLog()).toEqual([FROZEN_PRE_COMMIT_ARGS]);
	});

	it("pre-commit aborts when the dispatcher exits non-zero", async () => {
		const result = await runHook("pre-commit", [], { STUB_EXIT_CLI: "3" });

		expect(result.exitCode).toBe(1);
		expect(result.stdout).toContain("pre-commit FAILED");
		// The dispatcher really was invoked — the abort is a propagated failure,
		// not a hook that never ran anything.
		expect(await readArgsLog()).toEqual([FROZEN_PRE_COMMIT_ARGS]);
	});

	// ── pre-push ──────────────────────────────────────────────────────────────
	// The pre-push shim execs the SAME dispatcher entry point as pre-commit but
	// forwards its OWN hook name (`hooks run pre-push`). The dispatcher — not the
	// shim — decides which sections run from the `hooks:` config. The stub logs
	// `$*` as ONE line, so a single invocation is a single-element argsLog.

	it("pre-push invokes the dispatcher with the frozen `hooks run` args", async () => {
		const result = await runHook("pre-push");

		expect(result.exitCode).toBe(0);
		expect(await readArgsLog()).toEqual([FROZEN_PRE_PUSH_ARGS]);
	});

	it("pre-push aborts when the dispatcher exits non-zero", async () => {
		const result = await runHook("pre-push", [], { STUB_EXIT_CLI: "5" });

		expect(result.exitCode).toBe(1);
		expect(result.stdout).toContain("pre-push FAILED");
		// The dispatcher really ran before the propagated abort.
		expect(await readArgsLog()).toEqual([FROZEN_PRE_PUSH_ARGS]);
	});
});
